name: submit-problem

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
      SECRET_OJD_ID: ${{ secrets.OJD_ID }}
      SECRET_OJD_PASSWD: ${{ secrets.OJD_PASSWD }}
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - run: echo "yocto minimal"
    - uses: actions/checkout@v3
    - name: Fetch dependency
      run: sudo apt install build-essential chrpath gawk git bmap-tools texinfo diffstat tree zstd liblz4-tool chrpath diffstat
    - name: Set build env
      run: echo "CUR_DIR=$(pwd)" >> "$GITHUB_ENV"
    - name: Clone toolchain
      run: git clone https://github.com/arafat-hasan/uva-tool.git
    - name: Patch toolchain
      run: |
        pwd
        ls -al
        cd $CUR_DIR/uva-tool
        git apply $CUR_DIR/script/0001-Patch-uva-tool-direct-login.patch
        curl google.com
        chmod +x install.sh 
        ./install.sh
        echo "login using github action secret variable"
        echo  $SECRET_OJD_ID
        echo  $SECRET_OJD_PASSWD
        uva-tool -login $SECRET_OJD_ID $SECRET_OJD_PASSWD
